services:
  festival-api:
    build:
      context: .
      dockerfile: FestivalShoppingApi.Dockerfile
    container_name: festival_api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`seanofthe.dev`) && PathPrefix(`/festival-shopping-api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=/data/FestivalShopping.db
    volumes:
      - festivalist-data:/data
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
  app-network:
    driver: bridge
    
volumes:
  festivalist-data:
    name: festivalist-data
    driver: local