services:
  festival-api:
    build:
      context: .
      dockerfile: FestivalShoppingApi.Dockerfile
    container_name: festival_api_local
    labels: []
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/data/FestivalShopping.db
    volumes:
      - festival-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  festival-data:
    driver: local
